/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 zombie.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/zombie.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Yaku_zombie">
            <skinnedMesh name="Yaku_zombie_1" geometry={nodes.Yaku_zombie_1.geometry} material={materials.yaku_zombie_material} skeleton={nodes.Yaku_zombie_1.skeleton} />
            <skinnedMesh name="Yaku_zombie_2" geometry={nodes.Yaku_zombie_2.geometry} material={materials.yifu} skeleton={nodes.Yaku_zombie_2.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/zombie.glb')
